build:
  define_macros: []
  extra_compile_args: []
  include_dirs: []
  libraries: []
  library_dirs: []
  undef_macros: []
info:
  github_username: mdpiper
  plugin_author: Mark Piper
  plugin_license: MIT
  summary: PyMT plugin for FaSTMECH
library:
  entry_point:
  - FaSTMECH=bmifastmech:bmi_fastmech
  language: fortran
  register: ''
plugin:
  name: fastmech
  requirements:
  - fastmech
  - iriclib=0.1
  - cgns=3.2.1
  - hdf5=1.8.20
